---
- hosts: CDH

  tasks:

    - name: Share ssh keys with all nodes...
      shell:
        cmd: ./sshcopyid.sh
        chdir: ~/bscan/bash/node

- hosts: NODES

  vars:
    USER: iwillnotmakeaname
    SMBPASS: 07n3v88
    BSCANMOUNT: /home/iwillnotmakeaname/bscan
    BSCANSHARE: //10.142.0.6/bscan

  tasks:

# Update and get the nodemount/ share mounted

    - name: Updating node...
      become: yes
      package:
        update_cache: yes
    - name: Installing cifs-utils...
      become: yes
      package:
        name: cifs-utils
        state: latest

    - name: Installing dig...
      package:
        name: dnsutils
        state: latest

    - name: Check if bscan directory exists...
      stat:
        path: "{{ BSCANMOUNT }}"
      register: bscan_folder

    - name: Create the ~/bscan/ directory...
      file:
        path: "{{ BSCANMOUNT }}"
        state: directory
        mode: '0755'
      when: bscan_folder.stat.exists == false
    - name: Mount the nodemount folder...
      become: yes
      mount:
        path: "{{ BSCANMOUNT }}"
        src: "{{ BSCANSHARE }}"
        fstype: cifs
        opts: rw,uid=1000,gid=1001,username={{ USER }},password={{ SMBPASS }}
        state: mounted

# Get massdns ready to rock

    - name: Copy massdns to local node...
      shell:
        cmd: cp -rf ~/bscan/tools/massdns ~/
        chdir: ~/

# Get massdns ready to rock

    - name: Copy massdns to local node...
      shell:
        cmd: cp -rf ~/bscan/tools/massdns ~/
        chdir: ~/

# Get dnsgen ready to rock

    - name: Copy dnsgen to local node...
      shell:
        cmd: "cp -rf dnsgen ~/"
        chdir: ~/bscan/tools
    - name: Install pip3...
      become: yes
      package:
        name: python3-pip
        state: latest
    - name: Install python dependency stuff...
      become: yes
      shell:
        cmd: pip3 install idna==2.7
        chdir: ~/
    - name: Installing dnsgen requirements...
      shell:
        cmd: "pip3 install -r requirements.txt"
        chdir: ~/dnsgen
    - name:  Installing dnsgen...
      become: yes
      shell:
        cmd: "python3 setup.py install"
        chdir: /home/{{ USER }}/dnsgen

# Copy over noderunfreshdomains.sh script

    - name: Copy nodesrunfreshdomains.sh script over...
      shell:
        cmd: cp nodesrunfreshdomains.sh ~/runfreshdomains.sh
        chdir: ~/bscan/bash/node/

    - name: Copy nodesdigdomains.sh script over...
      shell:
        cmd: cp nodesdigdomains.sh ~/digdomains.sh
        chdir: ~/bscan/bash/node/

    - name: Copy nodescurldomains.sh script over...
      shell:
        cmd: cp nodescurldomains.sh ~/curldomains.sh
        chdir: ~/bscan/bash/node/


